image: node:5.10.1

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - mkdir .public
  - cp index.html .public
  - cp index.min.js .public
  - cp styles.css .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master