pages:
  stage: deploy
  script:
  - mkdir .public
  - cp index.html .public
  - cp index.js .public
  - cp style.css .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master